### ISSUE TITLE
Build error on 300-pwn 

### ISSUE THREAD

**Issue by lesliesmith** [BSidesPDX/CTF-2020#1]
I downloaded the ctf site about 12:01PM.  Attemptes to build the ctf server got a build error.  The last couple of lines listed were :
Step 15/18 : COPY ./speakers /home/ctf/
ERROR: Service '300-pwn' failed to build : COPY failed: stat /var/lib/docker/tmp/docker-builder914454293/speakers: no such file or directory

A brief look at the dockerfile seemed to indicate that the speaker.c file was compiled (separately not in the container), but the Dockerfile copy is from the dockerfile src directory where it is not found.  There is an apparently compiled copy in the ../distFiles directory and one in the ../solve directory but the version in the src directory was removed.  It isn't clear if these would be the correct version or format.  The start_challenge.sh file is not used by the docker_compose.yml / Dockerfile combination included.

When I copied one of the other speakers files to the src directory and restarted with docker-compose up -d,
the build completed successfully.  

What isn't clear is if the speakers file will actually work as expected on the new build.

**Comment by aagallag** [comment]
Good catch @lesliesmith

Fixed in 29dfb4358c625e6604999649a75f67f0c9a14358
